export const movingSizes = [
  { value: 'Room on less', label: 'Room on less' },
  { value: 'Studio Apartment', label: 'Studio Apartment' },
  { value: '1 Bedroom Apartment', label: '1 Bedroom Apartment' },
  { value: '2 Bedroom Apartment', label: '2 Bedroom Apartment' },
  { value: '3 Bedroom Apartment', label: '3 Bedroom Apartment' },
  { value: '1 Bedroom House', label: '1 Bedroom House' },
  { value: '1 Bedroom House (Large)', label: '1 Bedroom House (Large)' },
  { value: '2 Bedroom House', label: '2 Bedroom House' },
  { value: '2 Bedroom House (Large)', label: '2 Bedroom House (Large)' },
  { value: '3 Bedroom House', label: '3 Bedroom House' },
  { value: '3 Bedroom House (Large)', label: '3 Bedroom House (Large)' },
  { value: '4 Bedroom House', label: '4 Bedroom House' },
  { value: '4 Bedroom House (Large)', label: '4 Bedroom House (Large)' },
  { value: '5 Bedroom House', label: '5 Bedroom House' },
  { value: '5 Bedroom House (Large)', label: '5 Bedroom House (Large)' },
  { value: '5 x 10 Storage Unit', label: '5 x 10 Storage Unit' },
  { value: '5 x 15 Storage Unit', label: '5 x 15 Storage Unit' },
  { value: '10 x 10 Storage Unit', label: '10 x 10 Storage Unit' },
  { value: '10 x 15 Storage Unit', label: '10 x 15 Storage Unit' },
  { value: '10 x 20 Storage Unit', label: '10 x 20 Storage Unit' },
];
